<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA12MCZa\App_KernelTestsDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA12MCZa/App_KernelTestsDebugContainer.php') {
    touch(__DIR__.'/ContainerA12MCZa.legacy');

    return;
}

if (!\class_exists(App_KernelTestsDebugContainer::class, false)) {
    \class_alias(\ContainerA12MCZa\App_KernelTestsDebugContainer::class, App_KernelTestsDebugContainer::class, false);
}

return new \ContainerA12MCZa\App_KernelTestsDebugContainer([
    'container.build_hash' => 'A12MCZa',
    'container.build_id' => '26d3db62',
    'container.build_time' => 1684376849,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA12MCZa');
