imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*, src/Markdown/*, src/Kernel, src/php-cs-fixer.dist]

    # excluded_paths: [vendor/*, tests/*, src/Helpers/*, src/Entity/*, src/Repository/*, src/Markdown/*, src/Controller/LibraryController, src/Kernel, src/Controller/ProductController, src/php-cs-fixer.dist]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.1.13
                    # version: 8.1.17
                    # version: 8.2.4
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    tests:
        override:
            -
                command: "composer phpunit"
                # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
