<?php

namespace ContainerRAaxae6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DD9JOvLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dD9JOvL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dD9JOvL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
            'handler' => ['privates', 'App\\Library\\LibraryHandler', 'getLibraryHandlerService', true],
        ], [
            'bookRepository' => 'App\\Repository\\BookRepository',
            'handler' => 'App\\Library\\LibraryHandler',
        ]);
    }
}
