<?php

namespace ContainerRAaxae6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Helpers\JsonHandler' shared autowired service.
     *
     * @return \App\Helpers\JsonHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Helpers/JsonHandler.php';

        return $container->privates['App\\Helpers\\JsonHandler'] = new \App\Helpers\JsonHandler();
    }
}
