<?php

namespace ContainerRBSDVbO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TbQnfRDService extends App_KernelTestsDebugContainer
{
    /**
     * Gets the private '.service_locator.TbQnfRD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TbQnfRD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cardHandler' => ['privates', 'App\\Cards\\CardHandler', 'getCardHandlerService', true],
            'player' => ['privates', 'App\\Cards\\Player', 'getPlayerService', true],
        ], [
            'cardHandler' => 'App\\Cards\\CardHandler',
            'player' => 'App\\Cards\\Player',
        ]);
    }
}
