<?php

namespace ContainerRBSDVbO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookRemoverService extends App_KernelTestsDebugContainer
{
    /**
     * Gets the private 'App\Library\BookRemover' shared autowired service.
     *
     * @return \App\Library\BookRemover
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Library/BookRemover.php';

        return $container->privates['App\\Library\\BookRemover'] = new \App\Library\BookRemover();
    }
}
