<?php

namespace ContainerRBSDVbO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardLandingControllerService extends App_KernelTestsDebugContainer
{
    /**
     * Gets the public 'App\Controller\CardLandingController' shared autowired service.
     *
     * @return \App\Controller\CardLandingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CardLandingController.php';

        $container->services['App\\Controller\\CardLandingController'] = $instance = new \App\Controller\CardLandingController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\CardLandingController', $container));

        return $instance;
    }
}
