<?php

namespace ContainerRBSDVbO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardHandService extends App_KernelTestsDebugContainer
{
    /**
     * Gets the private 'App\Cards\CardHand' shared autowired service.
     *
     * @return \App\Cards\CardHand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Cards/CardHand.php';

        return $container->privates['App\\Cards\\CardHand'] = new \App\Cards\CardHand();
    }
}
