<?php

namespace ContainerRBSDVbO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoundHandlerService extends App_KernelTestsDebugContainer
{
    /**
     * Gets the private 'App\Game\RoundHandler' shared autowired service.
     *
     * @return \App\Game\RoundHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Game/RoundHandler.php';

        return $container->privates['App\\Game\\RoundHandler'] = new \App\Game\RoundHandler();
    }
}
