<?php

namespace ContainerRBSDVbO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Extension_MarkdownService extends App_KernelTestsDebugContainer
{
    /**
     * Gets the private 'twig.extension.markdown' shared service.
     *
     * @return \Twig\Extra\Markdown\MarkdownExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/markdown-extra/MarkdownExtension.php';

        return $container->privates['twig.extension.markdown'] = new \Twig\Extra\Markdown\MarkdownExtension();
    }
}
