<?php

namespace ContainerRBSDVbO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebpackEncore_TwigStimulusExtensionService extends App_KernelTestsDebugContainer
{
    /**
     * Gets the private 'webpack_encore.twig_stimulus_extension' shared service.
     *
     * @return \Symfony\WebpackEncoreBundle\Twig\StimulusTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/webpack-encore-bundle/src/Twig/StimulusTwigExtension.php';

        return $container->privates['webpack_encore.twig_stimulus_extension'] = new \Symfony\WebpackEncoreBundle\Twig\StimulusTwigExtension();
    }
}
