<?php

namespace ContainerS9Zu0CK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBanksTurnHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Game\BanksTurnHandler' shared autowired service.
     *
     * @return \App\Game\BanksTurnHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Game/BanksTurnHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Game/RoundHandler.php';

        return $container->privates['App\\Game\\BanksTurnHandler'] = new \App\Game\BanksTurnHandler(($container->privates['App\\Game\\RoundHandler'] ?? ($container->privates['App\\Game\\RoundHandler'] = new \App\Game\RoundHandler())));
    }
}
