<?php

namespace ContainerS9Zu0CK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameMoneyHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Game\GameMoneyHandler' shared autowired service.
     *
     * @return \App\Game\GameMoneyHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Game/GameMoneyHandler.php';

        return $container->privates['App\\Game\\GameMoneyHandler'] = new \App\Game\GameMoneyHandler();
    }
}
