services:
  App\Controller\SqlFileLoader:
    public: true
  App\Cards\DeckOfCards:
    public: true
  App\Cards\Player:
    public: true
  App\Controller\MdParser:
    public: true
  App\Game\NextRound:
    public: true
  App\Game\EndRound:
    public: true

      