<?php

namespace ContainerA12MCZa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonCardHandlerService extends App_KernelTestsDebugContainer
{
    /**
     * Gets the private 'App\Cards\JsonCardHandler' shared autowired service.
     *
     * @return \App\Cards\JsonCardHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Cards/JsonCardHandler.php';

        return $container->privates['App\\Cards\\JsonCardHandler'] = new \App\Cards\JsonCardHandler();
    }
}
