<?php

namespace ContainerA12MCZa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLibraryHandlerService extends App_KernelTestsDebugContainer
{
    /**
     * Gets the private 'App\Library\LibraryHandler' shared autowired service.
     *
     * @return \App\Library\LibraryHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Library/LibraryHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Library/BookSaver.php';
        include_once \dirname(__DIR__, 4).'/src/Library/BookUpdator.php';
        include_once \dirname(__DIR__, 4).'/src/Library/BookRemover.php';

        return $container->privates['App\\Library\\LibraryHandler'] = new \App\Library\LibraryHandler(new \App\Library\BookSaver(), new \App\Library\BookUpdator(), new \App\Library\BookRemover());
    }
}
