<?php

namespace ContainerPTkpsj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WaMDEoPService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.WaMDEoP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WaMDEoP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cardHandler' => ['privates', 'App\\Cards\\JsonCardHandler', 'getJsonCardHandlerService', true],
            'converter' => ['privates', 'App\\Helpers\\JsonConverter', 'getJsonConverterService', true],
            'player' => ['privates', 'App\\Cards\\Player', 'getPlayerService', true],
        ], [
            'cardHandler' => 'App\\Cards\\JsonCardHandler',
            'converter' => 'App\\Helpers\\JsonConverter',
            'player' => 'App\\Cards\\Player',
        ]);
    }
}
