<?php

namespace ContainerPTkpsj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookSaverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Library\BookSaver' shared autowired service.
     *
     * @return \App\Library\BookSaver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Library/BookSaver.php';

        return $container->privates['App\\Library\\BookSaver'] = new \App\Library\BookSaver();
    }
}
