<?php

namespace ContainerPTkpsj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookUpdatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Library\BookUpdator' shared autowired service.
     *
     * @return \App\Library\BookUpdator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Library/BookUpdator.php';

        return $container->privates['App\\Library\\BookUpdator'] = new \App\Library\BookUpdator();
    }
}
