<?php

namespace ContainerPTkpsj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonCardDealControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\JsonCardDealController' shared autowired service.
     *
     * @return \App\Controller\JsonCardDealController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/JsonCardDealController.php';

        $container->services['App\\Controller\\JsonCardDealController'] = $instance = new \App\Controller\JsonCardDealController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\JsonCardDealController', $container));

        return $instance;
    }
}
