<?php

namespace ContainerSZnCADN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vq74bGkService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.vq74bGk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vq74bGk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'converter' => ['privates', 'App\\Helpers\\JsonConverter', 'getJsonConverterService', true],
            'gameHandler' => ['privates', 'App\\Game\\JsonGameHandler', 'getJsonGameHandlerService', true],
        ], [
            'converter' => 'App\\Helpers\\JsonConverter',
            'gameHandler' => 'App\\Game\\JsonGameHandler',
        ]);
    }
}
