<?php

namespace ContainerSZnCADN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ALUTAService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.aLUT_A_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aLUT_A_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'gameHandler' => ['privates', 'App\\Game\\GameInitiator', 'getGameInitiatorService', true],
        ], [
            'gameHandler' => 'App\\Game\\GameInitiator',
        ]);
    }
}
