<?php

namespace ContainerSZnCADN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardLandingHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Cards\CardLandingHandler' shared autowired service.
     *
     * @return \App\Cards\CardLandingHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Cards/CardLandingHandler.php';

        return $container->privates['App\\Cards\\CardLandingHandler'] = new \App\Cards\CardLandingHandler();
    }
}
