<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6RsRuHT\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6RsRuHT/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container6RsRuHT.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container6RsRuHT\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container6RsRuHT\App_KernelTestDebugContainer([
    'container.build_hash' => '6RsRuHT',
    'container.build_id' => '5f7ccd5c',
    'container.build_time' => 1687918697,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6RsRuHT');
