<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxrnypp\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxrnypp/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerAxrnypp.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerAxrnypp\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerAxrnypp\App_KernelTestDebugContainer([
    'container.build_hash' => 'Axrnypp',
    'container.build_id' => 'd6e25d3b',
    'container.build_time' => 1685740369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxrnypp');
