<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2xmClVb\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2xmClVb/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container2xmClVb.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container2xmClVb\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container2xmClVb\App_KernelTestDebugContainer([
    'container.build_hash' => '2xmClVb',
    'container.build_id' => 'acfe61f8',
    'container.build_time' => 1687363520,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2xmClVb');
