DROP TABLE IF EXISTS "transaction";
DROP TABLE IF EXISTS "score";
DROP TABLE IF EXISTS "user";

CREATE TABLE IF NOT EXISTS score (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    registered DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    points INTEGER NOT NULL,
    CONSTRAINT FK_3299375158E0A285 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS "transaction" (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    registered DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    descr VARCHAR(100) NOT NULL, amount INTEGER NOT NULL, CONSTRAINT FK_723705D158E0A285 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE
);

INSERT INTO "transaction" VALUES(1,1,'2023-06-18','Free registration bonus',1000);

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    acronym VARCHAR(50) NOT NULL UNIQUE,
    hash VARCHAR(100) NOT NULL
);

INSERT INTO user VALUES(1,'doe@bth.se','John Doe','$2y$10$bh4KbO6upQywlhconQZf1.0UMbpV1qnhVy3WRa7wd2/2KlsjPq.AW');
