<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1uYMRqx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1uYMRqx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1uYMRqx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1uYMRqx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1uYMRqx\App_KernelDevDebugContainer([
    'container.build_hash' => '1uYMRqx',
    'container.build_id' => '01de8d03',
    'container.build_time' => 1707649434,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1uYMRqx');
