<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container35lMgTe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container35lMgTe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container35lMgTe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container35lMgTe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container35lMgTe\App_KernelDevDebugContainer([
    'container.build_hash' => '35lMgTe',
    'container.build_id' => 'd7dd1f0b',
    'container.build_time' => 1687428335,
], __DIR__.\DIRECTORY_SEPARATOR.'Container35lMgTe');
