<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.61b1725c.js',
                'build/751.7f9c0d93.js',
                'build/app.03692de2.js',
            ],
            'css' => [
                'build/app.18fed0ac.css',
            ],
        ],
    ],
],

]];
